# Docker Compose 开发环境配置
version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: dataquery-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENV=development
      - CONFIG_DIR=/app/config
    volumes:
      - ./api:/app
      - ./data:/app/data
      - ./config:/app/config
      - ./temp_files:/app/temp_files
      - ./exports:/app/exports
    networks:
      - dataquery-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端开发服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dataquery-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://dataquery-backend:8000
      - REACT_APP_UI_MODE=modern
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DOCKER_ENV=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dataquery-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  dataquery-network:
    driver: bridge
